[package]
name = "seismic-cuda"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
seismic-ir.workspace = true
seismic-estimator.workspace = true
seismic-lang.workspace = true
seismic-native-target.workspace = true
seismic-compiler.workspace = true
libloading = "0.8.9"
sha2 = "=0.11.0"
