// The representation ladder of the expert-stacked `expert_up` weight of the
// general routed entries: EU_KIND (a PACKETS_* kind) and EU_GEOMETRY (its
// rows16 geometry). GLSL has no templates, so the kind is selected here once
// for every entry binding `expert_up`; Metal and CUDA bind it through their
// `packets` slots. Include it only from entries that bind `expert_up`.

#if defined(SEISMIC_EXPERT_UP_REPRESENTATION_Q4K)
#define EU_KIND PACKETS_Q4K
#define EU_GEOMETRY PACKETS_ROWS16_Q4K(SEISMIC_EXPERT_UP)
#elif defined(SEISMIC_EXPERT_UP_REPRESENTATION_Q5K)
#define EU_KIND PACKETS_Q5K
#define EU_GEOMETRY PACKETS_ROWS16_HIGH(SEISMIC_EXPERT_UP)
#elif defined(SEISMIC_EXPERT_UP_REPRESENTATION_Q6K)
#define EU_KIND PACKETS_Q6K
#define EU_GEOMETRY PACKETS_ROWS16_HIGH(SEISMIC_EXPERT_UP)
#elif defined(SEISMIC_EXPERT_UP_REPRESENTATION_Q8G32S)
#define EU_KIND PACKETS_Q8
#define EU_GEOMETRY PACKETS_ROWS16_Q8(SEISMIC_EXPERT_UP)
#elif defined(SEISMIC_EXPERT_UP_REPRESENTATION_IQ4G32)
#define EU_KIND PACKETS_IQ4
#define EU_GEOMETRY PACKETS_ROWS16_C4(SEISMIC_EXPERT_UP)
#elif defined(SEISMIC_EXPERT_UP_REPRESENTATION_Q4G32S)
#define EU_KIND PACKETS_Q4G32S
#define EU_GEOMETRY PACKETS_ROWS16_C4(SEISMIC_EXPERT_UP)
#elif defined(SEISMIC_EXPERT_UP_REPRESENTATION_MXFP4G32)
#define EU_KIND PACKETS_MXFP4
#define EU_GEOMETRY PACKETS_ROWS16_C4(SEISMIC_EXPERT_UP)
#elif defined(SEISMIC_EXPERT_UP_REPRESENTATION_NVFP4G16)
#define EU_KIND PACKETS_NVFP4
#define EU_GEOMETRY PACKETS_ROWS16_C4(SEISMIC_EXPERT_UP)
#elif defined(SEISMIC_EXPERT_UP_REPRESENTATION_Q5G32S)
#define EU_KIND PACKETS_Q5G32S
#define EU_GEOMETRY PACKETS_ROWS16_Q5(SEISMIC_EXPERT_UP)
#elif defined(SEISMIC_EXPERT_UP_REPRESENTATION_Q5G32)
#define EU_KIND PACKETS_Q5G32
#define EU_GEOMETRY PACKETS_ROWS16_Q5(SEISMIC_EXPERT_UP)
#elif defined(SEISMIC_EXPERT_UP_REPRESENTATION_BF16)
#define EU_KIND PACKETS_BF16
#define EU_GEOMETRY ROUTED_EXPERT_ROWS_DENSE(SEISMIC_EXPERT_UP,2)
#elif defined(SEISMIC_EXPERT_UP_REPRESENTATION_F16)
#define EU_KIND PACKETS_F16
#define EU_GEOMETRY ROUTED_EXPERT_ROWS_DENSE(SEISMIC_EXPERT_UP,2)
#elif defined(SEISMIC_EXPERT_UP_REPRESENTATION_F32)
#define EU_KIND PACKETS_F32
#define EU_GEOMETRY ROUTED_EXPERT_ROWS_DENSE(SEISMIC_EXPERT_UP,4)
#else
#error "unsupported routed expert_up representation"
#endif
#if defined(SEISMIC_EXPERT_UP_KIND_PACKED) && !defined(SEISMIC_EXPERT_UP_LAYOUT_ROWS16)
#error "routed entries require the rows16 layout for expert_up"
#endif
