// The representation ladder of the expert-stacked `expert_gate` weight of the
// general routed entries: EG_KIND (a PACKETS_* kind) and EG_GEOMETRY (its
// rows16 geometry). GLSL has no templates, so the kind is selected here once
// for every entry binding `expert_gate`; Metal and CUDA bind it through their
// `packets` slots. Include it only from entries that bind `expert_gate`.

#if defined(SEISMIC_EXPERT_GATE_REPRESENTATION_Q4K)
#define EG_KIND PACKETS_Q4K
#define EG_GEOMETRY PACKETS_ROWS16_Q4K(SEISMIC_EXPERT_GATE)
#elif defined(SEISMIC_EXPERT_GATE_REPRESENTATION_Q5K)
#define EG_KIND PACKETS_Q5K
#define EG_GEOMETRY PACKETS_ROWS16_HIGH(SEISMIC_EXPERT_GATE)
#elif defined(SEISMIC_EXPERT_GATE_REPRESENTATION_Q6K)
#define EG_KIND PACKETS_Q6K
#define EG_GEOMETRY PACKETS_ROWS16_HIGH(SEISMIC_EXPERT_GATE)
#elif defined(SEISMIC_EXPERT_GATE_REPRESENTATION_Q8G32S)
#define EG_KIND PACKETS_Q8
#define EG_GEOMETRY PACKETS_ROWS16_Q8(SEISMIC_EXPERT_GATE)
#elif defined(SEISMIC_EXPERT_GATE_REPRESENTATION_IQ4G32)
#define EG_KIND PACKETS_IQ4
#define EG_GEOMETRY PACKETS_ROWS16_C4(SEISMIC_EXPERT_GATE)
#elif defined(SEISMIC_EXPERT_GATE_REPRESENTATION_Q4G32S)
#define EG_KIND PACKETS_Q4G32S
#define EG_GEOMETRY PACKETS_ROWS16_C4(SEISMIC_EXPERT_GATE)
#elif defined(SEISMIC_EXPERT_GATE_REPRESENTATION_MXFP4G32)
#define EG_KIND PACKETS_MXFP4
#define EG_GEOMETRY PACKETS_ROWS16_C4(SEISMIC_EXPERT_GATE)
#elif defined(SEISMIC_EXPERT_GATE_REPRESENTATION_NVFP4G16)
#define EG_KIND PACKETS_NVFP4
#define EG_GEOMETRY PACKETS_ROWS16_C4(SEISMIC_EXPERT_GATE)
#elif defined(SEISMIC_EXPERT_GATE_REPRESENTATION_Q5G32S)
#define EG_KIND PACKETS_Q5G32S
#define EG_GEOMETRY PACKETS_ROWS16_Q5(SEISMIC_EXPERT_GATE)
#elif defined(SEISMIC_EXPERT_GATE_REPRESENTATION_Q5G32)
#define EG_KIND PACKETS_Q5G32
#define EG_GEOMETRY PACKETS_ROWS16_Q5(SEISMIC_EXPERT_GATE)
#elif defined(SEISMIC_EXPERT_GATE_REPRESENTATION_BF16)
#define EG_KIND PACKETS_BF16
#define EG_GEOMETRY ROUTED_EXPERT_ROWS_DENSE(SEISMIC_EXPERT_GATE,2)
#elif defined(SEISMIC_EXPERT_GATE_REPRESENTATION_F16)
#define EG_KIND PACKETS_F16
#define EG_GEOMETRY ROUTED_EXPERT_ROWS_DENSE(SEISMIC_EXPERT_GATE,2)
#elif defined(SEISMIC_EXPERT_GATE_REPRESENTATION_F32)
#define EG_KIND PACKETS_F32
#define EG_GEOMETRY ROUTED_EXPERT_ROWS_DENSE(SEISMIC_EXPERT_GATE,4)
#else
#error "unsupported routed expert_gate representation"
#endif
#if defined(SEISMIC_EXPERT_GATE_KIND_PACKED) && !defined(SEISMIC_EXPERT_GATE_LAYOUT_ROWS16)
#error "routed entries require the rows16 layout for expert_gate"
#endif
