if(NOT DEFINED ICN_PARITY_ORACLE_SOURCE_DIR OR ICN_PARITY_ORACLE_SOURCE_DIR STREQUAL "")
    message(FATAL_ERROR "ICN_PARITY_ORACLE_SOURCE_DIR must name the parity oracle source directory")
endif()

get_property(ICN_PARITY_ORACLE_INJECTED GLOBAL PROPERTY ICN_PARITY_ORACLE_INJECTED)
if(NOT ICN_PARITY_ORACLE_INJECTED)
    set_property(GLOBAL PROPERTY ICN_PARITY_ORACLE_INJECTED TRUE)
    add_subdirectory(
        "${ICN_PARITY_ORACLE_SOURCE_DIR}"
        "${CMAKE_BINARY_DIR}/parity-oracle"
    )
endif()
