"""Read-only physical configuration contracts. No engine or discovery dependency."""

from __future__ import annotations

from collections.abc import Sequence
from typing import Protocol


class MemoryConstraint(Protocol):
    @property
    def id(self) -> str: ...
    @property
    def domains(self) -> Sequence[str]: ...
    @property
    def maximum_bytes(self) -> int: ...


class MemoryDomain(Protocol):
    @property
    def id(self) -> str: ...
    @property
    def capacity_bytes(self) -> int: ...
    @property
    def kind(self) -> str: ...


class AllocationMode(Protocol):
    @property
    def domains(self) -> Sequence[str]: ...
    @property
    def max_allocation_bytes(self) -> int: ...


class ExecutionEndpoint(Protocol):
    @property
    def id(self) -> str: ...
    @property
    def device(self) -> str: ...
    @property
    def backend(self) -> str: ...
    @property
    def ordinal(self) -> int | None: ...
    @property
    def unavailable(self) -> Sequence[str]: ...
    @property
    def modes(self) -> Sequence[AllocationMode]: ...


class DeviceConfiguration(Protocol):
    @property
    def selected_endpoints(self) -> Sequence[ExecutionEndpoint]: ...
    @property
    def memory_domains(self) -> Sequence[MemoryDomain]: ...
    @property
    def memory_constraints(self) -> Sequence[MemoryConstraint]: ...
    @property
    def fingerprint(self) -> str: ...
