[package]
name = "seismic"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
seismic-lang.workspace = true
seismic-compiler.workspace = true
seismic-runtime.workspace = true
seismic-native-cpu.workspace = true
seismic-std.workspace = true
sha2 = "0.10"
self_cell = "1"
