#ifndef TEMPLATES_H
#define TEMPLATES_H

#include <stdint.h>

#if defined(_WIN32)
#define TEMPLATES_API __declspec(dllexport)
#else
#define TEMPLATES_API __attribute__((visibility("default")))
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Version 1. Handles are process-local IDs, never addresses. All template calls
 * are serialized by this implementation. Input spans are borrowed for the call.
 * Output buffers are library-owned until templates_buffer_release(owner).
 * Owner 0 denotes static storage (including allocation-failure diagnostics).
 * Caller initializes output/error structures to zero and releases each result.
 * All JSON operation payloads carry {"version":1,...}. */
typedef uint64_t templates_handle;
typedef struct templates_buffer {
    const uint8_t * data;
    uint64_t size;
    templates_handle owner;
} templates_buffer;

enum templates_status {
    TEMPLATES_OK = 0,
    TEMPLATES_INVALID_ARGUMENT = 1,
    TEMPLATES_INVALID_HANDLE = 2,
    TEMPLATES_OUT_OF_MEMORY = 3,
    TEMPLATES_NATIVE_ERROR = 4,
    TEMPLATES_VERSION_MISMATCH = 5
};

TEMPLATES_API uint32_t templates_abi_version(void);
TEMPLATES_API int32_t templates_build_info(templates_buffer * output, templates_buffer * error);
TEMPLATES_API int32_t templates_buffer_release(templates_handle owner);
TEMPLATES_API int32_t templates_template_create(const uint8_t * json, uint64_t size,
    templates_handle * output, templates_buffer * error);
TEMPLATES_API int32_t templates_template_release(templates_handle handle, templates_buffer * error);
TEMPLATES_API int32_t templates_template_inspect(templates_handle handle,
    templates_buffer * output, templates_buffer * error);
/* Raw authored rendering: no server message normalization or injected reasoning
 * controls. Payload: {version, context:{messages,...}, now:UTC_epoch_seconds}.
 * Context may not replace artifact special tokens. Output is UTF-8 prompt bytes. */
TEMPLATES_API int32_t templates_template_render(templates_handle handle,
    const uint8_t * json, uint64_t size, templates_buffer * output, templates_buffer * error);
/* Prepared requests retain all parser/grammar data independently of the template.
 * Request payload includes messages, tools, tool_choice, parallel_tool_calls,
 * template_arguments, optional json_schema, and explicit now. */
TEMPLATES_API int32_t templates_request_create(templates_handle template_handle,
    const uint8_t * json, uint64_t size, templates_handle * output, templates_buffer * error);
TEMPLATES_API int32_t templates_request_describe(templates_handle handle,
    templates_buffer * output, templates_buffer * error);
TEMPLATES_API int32_t templates_request_release(templates_handle handle, templates_buffer * error);

enum templates_event_kind {
    TEMPLATES_CONTENT = 1,
    TEMPLATES_REASONING = 2,
    TEMPLATES_TOOL_START = 3,
    TEMPLATES_TOOL_ARGUMENTS = 4,
    TEMPLATES_TOOL_COMPLETE = 5,
    TEMPLATES_FINISH = 6
};
enum templates_terminal_cause {
    TEMPLATES_NATURAL = 0,
    TEMPLATES_LENGTH = 1,
    TEMPLATES_USER_STOP = 2,
    TEMPLATES_CANCELLED = 3,
    TEMPLATES_FAILED = 4
};
typedef struct templates_event {
    uint32_t kind;
    uint32_t index;
    const uint8_t * text;
    uint64_t text_size;
    const uint8_t * id;
    uint64_t id_size;
} templates_event;
typedef struct templates_events {
    const templates_event * data;
    uint64_t size;
} templates_events;

/* Events and spans are borrowed until the next feed/finish/release on this stream.
 * Different streams do not invalidate each other's output. Tool-start text is
 * the complete name, id is the stable call ID. Argument/text events are deltas.
 * Finish index is templates_terminal_cause. All sizes count bytes.
 * A stream retains its prepared plan. A parse/resource failure poisons that stream.
 * max_output_bytes is a hard bound on accumulated generated bytes, including a
 * pending incomplete UTF-8 suffix; it must be in [1, 67108864]. */
TEMPLATES_API int32_t templates_stream_create(templates_handle request_handle,
    uint64_t max_output_bytes, templates_handle * output, templates_buffer * error);
TEMPLATES_API int32_t templates_stream_feed(templates_handle handle,
    const uint8_t * bytes, uint64_t size, templates_events * output, templates_buffer * error);
TEMPLATES_API int32_t templates_stream_finish(templates_handle handle,
    uint32_t cause, templates_events * output, templates_buffer * error);
TEMPLATES_API int32_t templates_stream_release(templates_handle handle, templates_buffer * error);

#ifdef __cplusplus
}
#endif
#endif
