[package]
name = "icn-utils"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
fs2.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
tempfile = "3.24.0"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = [
    "Win32_Foundation", "Win32_Globalization", "Win32_Security",
    "Win32_System_JobObjects", "Win32_System_Pipes", "Win32_System_Threading",
    "Win32_System_IO", "Win32_System_Ioctl", "Win32_Storage_FileSystem",
] }
