import mlx.core as mx

source: str

def in_tracing() -> bool: ...
def identity(array: mx.array) -> int: ...
def is_tracer(array: mx.array) -> bool: ...

class Node:
    @property
    def inputs(self) -> list[mx.array]: ...
    @property
    def outputs(self) -> list[mx.array]: ...
    @property
    def name(self) -> str: ...
    @property
    def arguments(self) -> tuple: ...
    @property
    def stream(self) -> mx.Stream: ...
    def apply(self, inputs: list[mx.array]) -> list[mx.array]: ...

def inspect(
    outputs: list[mx.array], boundaries: list[mx.array]
) -> tuple[list[Node], list[mx.array]]: ...
